### ISSUE TITLE
🛑 Quote Image API [/api/quote] is down

### ISSUE THREAD

**Issue by purrbot-status** [purrbot-site/Status#2]
In [`9559bf3`](https://github.com/purrbot-site/Status/commit/9559bf3bd0f5e16f487b02288e8dc7a5718d4088
), Quote Image API [/api/quote] (https://purrbot.site/api/quote) was **down**:
- HTTP code: 410
- Response time: 155 ms

**Comment by Andre601** [comment]
This was a false positive due to upptime still checking for `/api/quote` being present
