### ISSUE TITLE
🛑 Status Image API [/api/status] is down

### ISSUE THREAD

**Issue by purrbot-status** [purrbot-site/Status#3]
In [`c38236e`](https://github.com/purrbot-site/Status/commit/c38236eeb6bfabf55b40c53446afa9f20cffb681
), Status Image API [/api/status] (https://purrbot.site/api/status) was **down**:
- HTTP code: 410
- Response time: 155 ms

**Comment by Andre601** [comment]
This was a false positive due to upptime still checking for `/api/status` being present
